add fatemeh to team
volkamerlab/volkamerlab_org pull request #156
Opened 2024-05-16 14:16 UTC by fatemeh-moghaddam

2024-05-18 10:38 UTC, AndreaVolkamer requested changes
@fatemeh-moghaddam thanks for adding your info. Please double check, it seems like your picture is not showing on the website?

2024-05-18 10:39 UTC, AndreaVolkamer commented
@fatemeh-moghaddam you can check the rendering by clicking on `Details` in the **Checks** category under ´deploy/netlifly´

2024-05-21 10:01 UTC, fatemeh-moghaddam commented
@AndreaVolkamer Thank you for the hint. The picture format was .PNG and it should have been .JPG. It is solved now.

2024-05-22 14:13 UTC, AndreaVolkamer approved these changes

2024-05-22 14:13 UTC, merged