Hamza's blogposts and project update
volkamerlab/volkamerlab_org pull request #176
Opened 2024-11-13 13:44 UTC by hamzaibrahim21

### TODO

- [x] Add master thesis defense blogpost
- [x] Add lab joining as PhD blogpost
- [x] Add ECF-T paper blogpost
- [x] Update ECF-T VS pipeline to MolDockLab
- [x] Add MolDockLab figure

### Status

- [x] Ready to go

2024-11-13 15:14 UTC, PaulaKramer reviewed
Thanks a lot @hamzaibrahim21, I just added one small comment.

2024-11-13 15:14 UTC, PaulaKramer commented on content/blog/hamza_member.md
> +Hamza holds a bachelor's degree in Pharmaceutical Sciences and a master's degree in Bioinformatics from Saarland University, and he is joining as a PhD candidate. He completed his master's thesis in
Can you link MolDockLab here?

2024-11-14 08:41 UTC, hamzaibrahim21 commented
> Thanks a lot @hamzaibrahim21, I just added one small comment.

Thanks for the feedback, I've linked it to MolDockLab in projects

2024-11-15 11:52 UTC, AndreaVolkamer requested changes
@hamzaibrahim21 thanks for hte blogpost., Can you check the Moldocklab links, they do not work for me?

2024-11-15 20:58 UTC, hamzaibrahim21 commented
> @hamzaibrahim21 thanks for hte blogpost., Can you check the Moldocklab links, they do not work for me?

@AndreaVolkamer Thanks for the feedback, it didn't work remotely. However, the links should work now

2024-11-19 10:29 UTC, merged